FROM php:8.3-fpm


COPY --from=composer:latest /usr/bin/composer /usr/bin/composer


RUN apt-get update  \
    && apt-get install -y \
    git \
    unzip \
    libpq-dev \
    && docker-php-ext-install  \
    pdo  \
    pdo_pgsql \
    && pecl install \
    xdebug-3.4.1 \
    && docker-php-ext-enable  \
    xdebug



WORKDIR /var/www/html


CMD ["php-fpm"]