version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php_container
    volumes:
      - ./:/var/www/html
    # Порты для php напрямую обычно не выставляют наружу,
    # но иногда тебе может понадобиться xdebug, тогда добавляют соответствующие настройки
    # environment:
    #   XDEBUG_MODE: debug
    #   XDEBUG_CONFIG: remote_host=host.docker.internal

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:latest
    container_name: db_container
    environment:
      - POSTGRES_USER=symfony
      - POSTGRES_PASSWORD=symfony
      - POSTGRES_DB=symfony
    ports:
      - "5432:5432"
    # Если хочешь чтобы данные сохранялись (не пропадали при пересоздании контейнера):
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: